# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 06:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='news_item_source',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.NewsSource'),
            preserve_default=False,
        ),
    ]
